name: web3_webview
description: "The bridge communicate between in-app webview and mobile-app by standard EIP-1193."
version: 1.0.5
homepage: https://github.com/datit309309/web3_webview

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  hex: ^0.2.0
  http: ^1.3.0
  web3dart: ^2.7.3
  crypto: ^3.0.6
  modal_bottom_sheet: ^3.0.0
  clipboard: ^0.1.3
  intl: ^0.20.2
  uuid: ^4.5.1
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/web3_webview/assets/ethers.min.js